import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/common/header";
import Footer from "@/components/common/footer";

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Homepage | SCE",
    template: "%s | SCE",
  },
  description: "SCE generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sukhumvit">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
